"""
Semantic key question dictionary.

semantic_key is a stable identifier that crosses template boundaries.
Any PDF field tagged with a semantic_key gets a human-quality question
without per-form configuration.

SEMANTIC_QUESTIONS[key][locale] = {question, help, example, format}

LABEL_TO_SEMANTIC maps cleaned German original_label → semantic_key.
Applied as a post-extraction annotation — never changes field_id.
"""
from __future__ import annotations
from typing import Optional

# ── Semantic key → multi-language human question ──────────────────────────────

SEMANTIC_QUESTIONS: dict[str, dict[str, dict[str, str]]] = {

    # ── Person ────────────────────────────────────────────────────────────────

    "person.full_name": {
        "en": {"question": "What is your full name?",
               "help": "Write your last name first, then your first name, exactly as on your ID.",
               "example": "Bah Mamadou"},
        "fr": {"question": "Quel est votre nom complet ?",
               "help": "Écrivez votre nom de famille, puis votre prénom, comme sur votre document officiel.",
               "example": "Bah Mamadou"},
        "ar": {"question": "ما هو اسمك الكامل؟",
               "help": "اكتب اسمك الأخير أولاً ثم اسمك الأول، كما في وثيقة هويتك.",
               "example": "باه محمدو"},
        "tr": {"question": "Tam adınız nedir?",
               "help": "Önce soyadınızı, sonra adınızı resmi belgenizdeki gibi yazın.",
               "example": "Bah Mamadou"},
        "de": {"question": "Wie lautet Ihr vollständiger Name?",
               "help": "Zuerst Nachname, dann Vorname, wie auf dem Ausweis.",
               "example": "Müller, Anna"},
        "es": {"question": "¿Cuál es tu nombre completo?",
               "help": "Escribe primero tu apellido, luego tu nombre, como en tu documento.",
               "example": "Bah Mamadou"},
        "sq": {"question": "Cili është emri juaj i plotë?",
               "help": "Shkruani fillimisht mbiemrin, pastaj emrin.",
               "example": "Bah Mamadou"},
        "ru": {"question": "Как ваше полное имя?",
               "help": "Напишите фамилию, затем имя, как в документе.",
               "example": "Баh Мамаду"},
        "uk": {"question": "Як ваше повне ім'я?",
               "help": "Напишіть прізвище, потім ім'я, як в документі.",
               "example": "Бах Мамаду"},
    },

    "person.first_name": {
        "en": {"question": "What is your first name?",
               "help": "Write your first name exactly as it appears on your ID.",
               "example": "Mamadou"},
        "fr": {"question": "Quel est votre prénom ?",
               "help": "Écrivez votre prénom exactement comme sur votre pièce d'identité.",
               "example": "Mamadou"},
        "ar": {"question": "ما هو اسمك الأول؟",
               "help": "اكتب اسمك الأول كما يظهر في وثيقة هويتك.",
               "example": "محمدو"},
        "tr": {"question": "Adınız nedir?", "example": "Mamadou"},
        "de": {"question": "Wie lautet Ihr Vorname?", "example": "Anna"},
        "es": {"question": "¿Cuál es tu nombre?", "example": "Mamadou"},
        "sq": {"question": "Cili është emri juaj?", "example": "Mamadou"},
        "ru": {"question": "Как ваше имя?", "example": "Мамаду"},
        "uk": {"question": "Яке ваше ім'я?", "example": "Мамаду"},
    },

    "person.last_name": {
        "en": {"question": "What is your last name?",
               "help": "Write your family name as it appears on your ID.",
               "example": "Bah"},
        "fr": {"question": "Quel est votre nom de famille ?", "example": "Bah"},
        "ar": {"question": "ما هو اسم عائلتك؟", "example": "باه"},
        "tr": {"question": "Soyadınız nedir?", "example": "Bah"},
        "de": {"question": "Wie lautet Ihr Nachname?", "example": "Müller"},
        "es": {"question": "¿Cuál es tu apellido?", "example": "Bah"},
        "sq": {"question": "Cili është mbiemri juaj?", "example": "Bah"},
        "ru": {"question": "Как ваша фамилия?", "example": "Баh"},
        "uk": {"question": "Яке ваше прізвище?", "example": "Бах"},
    },

    "person.birth_date": {
        "en": {"question": "What is your date of birth?",
               "format": "DD.MM.YYYY", "example": "15.03.1990"},
        "fr": {"question": "Quelle est votre date de naissance ?",
               "format": "JJ.MM.AAAA", "example": "15.03.1990"},
        "ar": {"question": "ما هو تاريخ ميلادك؟",
               "format": "يوم.شهر.سنة", "example": "15.03.1990"},
        "tr": {"question": "Doğum tarihiniz nedir?",
               "format": "GG.AA.YYYY", "example": "15.03.1990"},
        "de": {"question": "Wie lautet Ihr Geburtsdatum?",
               "format": "TT.MM.JJJJ", "example": "15.03.1990"},
        "es": {"question": "¿Cuál es tu fecha de nacimiento?",
               "format": "DD.MM.AAAA", "example": "15.03.1990"},
        "sq": {"question": "Cila është data juaj e lindjes?",
               "format": "DD.MM.VVVV", "example": "15.03.1990"},
        "ru": {"question": "Какова ваша дата рождения?",
               "format": "ДД.ММ.ГГГГ", "example": "15.03.1990"},
        "uk": {"question": "Яка ваша дата народження?",
               "format": "ДД.ММ.РРРР", "example": "15.03.1990"},
    },

    "person.birth_place": {
        "en": {"question": "What is your place of birth?", "example": "Rostock"},
        "fr": {"question": "Quel est votre lieu de naissance ?", "example": "Rostock"},
        "ar": {"question": "ما هو مكان ولادتك؟", "example": "روستوك"},
        "tr": {"question": "Doğum yeriniz nedir?", "example": "Rostock"},
        "de": {"question": "Wie lautet Ihr Geburtsort?", "example": "Rostock"},
        "es": {"question": "¿Cuál es tu lugar de nacimiento?", "example": "Rostock"},
        "sq": {"question": "Cili është vendi juaj i lindjes?", "example": "Rostock"},
        "ru": {"question": "Каково ваше место рождения?", "example": "Росток"},
        "uk": {"question": "Яке ваше місце народження?", "example": "Росток"},
    },

    "person.birth_name": {
        "en": {"question": "What is your birth name (maiden name)?",
               "help": "Your birth name is the name you had before marriage, if it changed."},
        "fr": {"question": "Quel est votre nom de naissance (nom de jeune fille) ?"},
        "ar": {"question": "ما هو اسم الولادة؟"},
        "tr": {"question": "Doğum adınız (kızlık soyadınız) nedir?"},
        "de": {"question": "Wie lautet Ihr Geburtsname (Mädchenname)?"},
        "es": {"question": "¿Cuál es tu nombre de nacimiento (apellido de soltera)?"},
        "sq": {"question": "Cili është emri juaj i lindjes (emri para martesës)?"},
        "ru": {"question": "Какова ваша девичья фамилия?"},
        "uk": {"question": "Яке ваше дівоче прізвище?"},
    },

    "person.nationality": {
        "en": {"question": "What is your nationality?", "example": "German, French, Turkish"},
        "fr": {"question": "Quelle est votre nationalité ?", "example": "Française, Allemande"},
        "ar": {"question": "ما هي جنسيتك؟", "example": "ألمانية، فرنسية"},
        "tr": {"question": "Uyruğunuz nedir?", "example": "Alman, Türk"},
        "de": {"question": "Was ist Ihre Staatsangehörigkeit?", "example": "Deutsch, Türkisch"},
        "es": {"question": "¿Cuál es tu nacionalidad?", "example": "Alemana, Española"},
        "sq": {"question": "Cila është shtetësia juaj?", "example": "Gjermane, Shqiptare"},
        "ru": {"question": "Какое у вас гражданство?", "example": "Немецкое, Российское"},
        "uk": {"question": "Яке ваше громадянство?", "example": "Німецьке, Українське"},
    },

    "person.gender": {
        "en": {"question": "What is your gender?", "help": "Select as it appears on your official documents."},
        "fr": {"question": "Quel est votre genre ?"},
        "ar": {"question": "ما هو جنسك؟"},
        "tr": {"question": "Cinsiyetiniz nedir?"},
        "de": {"question": "Was ist Ihr Geschlecht?"},
        "es": {"question": "¿Cuál es tu género?"},
        "sq": {"question": "Cili është gjinia juaj?"},
        "ru": {"question": "Какой у вас пол?"},
        "uk": {"question": "Яка ваша стать?"},
    },

    "person.marital_status": {
        "en": {"question": "What is your marital status?",
               "help": "Single, married, divorced, widowed, or civil partnership."},
        "fr": {"question": "Quelle est votre situation familiale ?"},
        "ar": {"question": "ما هي حالتك الاجتماعية؟"},
        "tr": {"question": "Medeni durumunuz nedir?"},
        "de": {"question": "Was ist Ihr Familienstand?"},
        "es": {"question": "¿Cuál es tu estado civil?"},
        "sq": {"question": "Cila është gjendja juaj civile?"},
        "ru": {"question": "Каково ваше семейное положение?"},
        "uk": {"question": "Який ваш сімейний стан?"},
    },

    # ── Address ───────────────────────────────────────────────────────────────

    "address.street": {
        "en": {"question": "What is your street name?", "example": "Musterstraße"},
        "fr": {"question": "Quelle est votre rue ?", "example": "Musterstraße"},
        "ar": {"question": "ما هو اسم شارعك؟", "example": "Musterstraße"},
        "tr": {"question": "Sokak adınız nedir?", "example": "Musterstraße"},
        "de": {"question": "Wie lautet Ihr Straßenname?", "example": "Musterstraße"},
        "es": {"question": "¿Cuál es el nombre de tu calle?", "example": "Musterstraße"},
        "sq": {"question": "Cila është rruga juaj?", "example": "Musterstraße"},
        "ru": {"question": "Как называется ваша улица?", "example": "Musterstraße"},
        "uk": {"question": "Яка назва вашої вулиці?", "example": "Musterstraße"},
    },

    "address.house_number": {
        "en": {"question": "What is your house number?", "example": "12 or 12a"},
        "fr": {"question": "Quel est votre numéro de maison ?", "example": "12"},
        "ar": {"question": "ما هو رقم منزلك؟", "example": "12"},
        "tr": {"question": "Kapı numaranız nedir?", "example": "12"},
        "de": {"question": "Wie lautet Ihre Hausnummer?", "example": "12"},
        "es": {"question": "¿Cuál es el número de tu casa?", "example": "12"},
        "sq": {"question": "Cili është numri i shtëpisë suaj?", "example": "12"},
        "ru": {"question": "Какой у вас номер дома?", "example": "12"},
        "uk": {"question": "Який ваш номер будинку?", "example": "12"},
    },

    "address.postal_code": {
        "en": {"question": "What is your postal code?",
               "help": "The 5-digit postal code for your address.",
               "format": "5 digits", "example": "18055"},
        "fr": {"question": "Quel est votre code postal ?",
               "format": "5 chiffres", "example": "18055"},
        "ar": {"question": "ما هو رمزك البريدي؟",
               "format": "5 أرقام", "example": "18055"},
        "tr": {"question": "Posta kodunuz nedir?",
               "format": "5 rakam", "example": "18055"},
        "de": {"question": "Wie lautet Ihre Postleitzahl?",
               "format": "5 Ziffern", "example": "18055"},
        "es": {"question": "¿Cuál es tu código postal?",
               "format": "5 dígitos", "example": "18055"},
        "sq": {"question": "Cili është kodi juaj postar?",
               "format": "5 shifra", "example": "18055"},
        "ru": {"question": "Какой у вас почтовый индекс?",
               "format": "5 цифр", "example": "18055"},
        "uk": {"question": "Який ваш поштовий індекс?",
               "format": "5 цифр", "example": "18055"},
    },

    "address.city": {
        "en": {"question": "What city or town do you live in?", "example": "Rostock"},
        "fr": {"question": "Dans quelle ville habitez-vous ?", "example": "Rostock"},
        "ar": {"question": "في أي مدينة أو بلدة تسكن؟", "example": "روستوك"},
        "tr": {"question": "Hangi şehir veya kasabada yaşıyorsunuz?", "example": "Rostock"},
        "de": {"question": "In welcher Stadt oder Gemeinde wohnen Sie?", "example": "Rostock"},
        "es": {"question": "¿En qué ciudad o pueblo vives?", "example": "Rostock"},
        "sq": {"question": "Në cilin qytet ose fshat jetoni?", "example": "Rostock"},
        "ru": {"question": "В каком городе или населённом пункте вы живёте?", "example": "Росток"},
        "uk": {"question": "В якому місті або населеному пункті ви живете?", "example": "Росток"},
    },

    "address.country": {
        "en": {"question": "What country do you live in?", "example": "Germany"},
        "fr": {"question": "Dans quel pays vivez-vous ?", "example": "Allemagne"},
        "ar": {"question": "في أي بلد تعيش؟", "example": "ألمانيا"},
        "tr": {"question": "Hangi ülkede yaşıyorsunuz?", "example": "Almanya"},
        "de": {"question": "In welchem Land wohnen Sie?", "example": "Deutschland"},
        "es": {"question": "¿En qué país vives?", "example": "Alemania"},
        "sq": {"question": "Në cilin vend jetoni?", "example": "Gjermani"},
        "ru": {"question": "В какой стране вы живёте?", "example": "Германия"},
        "uk": {"question": "В якій країні ви живете?", "example": "Німеччина"},
    },

    # ── Contact ───────────────────────────────────────────────────────────────

    "contact.phone": {
        "en": {"question": "What is your phone number?",
               "help": "Include the country code if calling from abroad.",
               "example": "+49 381 12345678"},
        "fr": {"question": "Quel est votre numéro de téléphone ?", "example": "+49 381 12345678"},
        "ar": {"question": "ما هو رقم هاتفك؟", "example": "+49 381 12345678"},
        "tr": {"question": "Telefon numaranız nedir?", "example": "+49 381 12345678"},
        "de": {"question": "Wie lautet Ihre Telefonnummer?", "example": "0381 12345678"},
        "es": {"question": "¿Cuál es tu número de teléfono?", "example": "+49 381 12345678"},
        "sq": {"question": "Cili është numri juaj i telefonit?", "example": "+49 381 12345678"},
        "ru": {"question": "Какой у вас номер телефона?", "example": "+49 381 12345678"},
        "uk": {"question": "Який ваш номер телефону?", "example": "+49 381 12345678"},
    },

    "contact.email": {
        "en": {"question": "What is your email address?", "example": "name@example.com"},
        "fr": {"question": "Quelle est votre adresse e-mail ?", "example": "nom@exemple.com"},
        "ar": {"question": "ما هو بريدك الإلكتروني؟", "example": "name@example.com"},
        "tr": {"question": "E-posta adresiniz nedir?", "example": "name@example.com"},
        "de": {"question": "Wie lautet Ihre E-Mail-Adresse?", "example": "name@beispiel.de"},
        "es": {"question": "¿Cuál es tu correo electrónico?", "example": "nombre@ejemplo.com"},
        "sq": {"question": "Cila është adresa juaj e emailit?", "example": "emri@shembull.com"},
        "ru": {"question": "Какой у вас адрес электронной почты?", "example": "имя@пример.ру"},
        "uk": {"question": "Яка ваша електронна пошта?", "example": "ім'я@приклад.ua"},
    },

    # ── Child ─────────────────────────────────────────────────────────────────

    "child.full_name": {
        "en": {"question": "What is the child's full name?",
               "help": "Last name first, then first name.", "example": "Müller, Lena"},
        "fr": {"question": "Quel est le nom complet de l'enfant ?", "example": "Müller, Lena"},
        "ar": {"question": "ما هو الاسم الكامل للطفل؟", "example": "مولر، لينا"},
        "tr": {"question": "Çocuğun tam adı nedir?", "example": "Müller, Lena"},
        "de": {"question": "Wie lautet der vollständige Name des Kindes?", "example": "Müller, Lena"},
        "es": {"question": "¿Cuál es el nombre completo del niño?", "example": "Müller, Lena"},
        "sq": {"question": "Cili është emri i plotë i fëmijës?", "example": "Müller, Lena"},
        "ru": {"question": "Как полное имя ребёнка?", "example": "Мюллер, Лена"},
        "uk": {"question": "Як повне ім'я дитини?", "example": "Мюллер, Лена"},
    },

    "child.birth_date": {
        "en": {"question": "What is the child's date of birth?",
               "format": "DD.MM.YYYY", "example": "12.03.2016"},
        "fr": {"question": "Quelle est la date de naissance de l'enfant ?",
               "format": "JJ.MM.AAAA", "example": "12.03.2016"},
        "ar": {"question": "ما هو تاريخ ميلاد الطفل؟",
               "format": "يوم.شهر.سنة", "example": "12.03.2016"},
        "tr": {"question": "Çocuğun doğum tarihi nedir?",
               "format": "GG.AA.YYYY", "example": "12.03.2016"},
        "de": {"question": "Wie lautet das Geburtsdatum des Kindes?",
               "format": "TT.MM.JJJJ", "example": "12.03.2016"},
        "es": {"question": "¿Cuál es la fecha de nacimiento del niño?",
               "format": "DD.MM.AAAA", "example": "12.03.2016"},
        "sq": {"question": "Cila është data e lindjes së fëmijës?",
               "format": "DD.MM.VVVV", "example": "12.03.2016"},
        "ru": {"question": "Какова дата рождения ребёнка?",
               "format": "ДД.ММ.ГГГГ", "example": "12.03.2016"},
        "uk": {"question": "Яка дата народження дитини?",
               "format": "ДД.ММ.РРРР", "example": "12.03.2016"},
    },

    "child.class_grade": {
        "en": {"question": "What class or grade is the child in?",
               "help": "Write the child's current school class.",
               "example": "Klasse 4A or Grade 4"},
        "fr": {"question": "Dans quelle classe est l'enfant ?",
               "example": "Classe 4A ou CM1"},
        "ar": {"question": "في أي صف دراسي الطفل؟",
               "example": "الصف الرابع أ"},
        "tr": {"question": "Çocuk kaçıncı sınıfta?",
               "example": "4A sınıfı"},
        "de": {"question": "In welcher Klasse ist das Kind?",
               "example": "Klasse 4A"},
        "es": {"question": "¿En qué clase o grado está el niño?",
               "example": "Clase 4A o 4° grado"},
        "sq": {"question": "Në cilin klas është fëmija?",
               "example": "Klasa 4A"},
        "ru": {"question": "В каком классе учится ребёнок?",
               "example": "4А класс"},
        "uk": {"question": "В якому класі навчається дитина?",
               "example": "4А клас"},
    },

    "child.school_year": {
        "en": {"question": "What school year is the child in?",
               "example": "2025/2026"},
        "fr": {"question": "En quelle année scolaire est l'enfant ?",
               "example": "2025/2026"},
        "ar": {"question": "ما هو العام الدراسي للطفل؟",
               "example": "2025/2026"},
        "tr": {"question": "Çocuğun okul yılı nedir?",
               "example": "2025/2026"},
        "de": {"question": "In welchem Schuljahr ist das Kind?",
               "example": "2025/2026"},
        "es": {"question": "¿En qué año escolar está el niño?",
               "example": "2025/2026"},
        "sq": {"question": "Në cilin vit shkollor është fëmija?",
               "example": "2025/2026"},
        "ru": {"question": "В каком учебном году учится ребёнок?",
               "example": "2025/2026"},
        "uk": {"question": "В якому навчальному році навчається дитина?",
               "example": "2025/2026"},
    },

    # ── School / Institution ──────────────────────────────────────────────────

    "school.name": {
        "en": {"question": "What is the name of the school the child attends?",
               "example": "Grundschule am Mühlenberg"},
        "fr": {"question": "Quel est le nom de l'école que fréquente l'enfant ?",
               "example": "Grundschule am Mühlenberg"},
        "ar": {"question": "ما هو اسم المدرسة التي يلتحق بها الطفل؟",
               "example": "Grundschule am Mühlenberg"},
        "tr": {"question": "Çocuğun gittiği okulun adı nedir?",
               "example": "Grundschule am Mühlenberg"},
        "de": {"question": "Wie heißt die Schule, die das Kind besucht?",
               "example": "Grundschule am Mühlenberg"},
        "es": {"question": "¿Cuál es el nombre de la escuela del niño?",
               "example": "Grundschule am Mühlenberg"},
        "sq": {"question": "Cili është emri i shkollës që ndjek fëmija?",
               "example": "Grundschule am Mühlenberg"},
        "ru": {"question": "Как называется школа, которую посещает ребёнок?",
               "example": "Grundschule am Mühlenberg"},
        "uk": {"question": "Як називається школа, яку відвідує дитина?",
               "example": "Grundschule am Mühlenberg"},
    },

    "institution.name": {
        "en": {"question": "What is the name of the school, kindergarten, or institution?",
               "example": "Grundschule am Mühlenberg"},
        "fr": {"question": "Quel est le nom de l'école, de la crèche ou de l'établissement ?",
               "example": "Grundschule am Mühlenberg"},
        "ar": {"question": "ما هو اسم المدرسة أو الحضانة أو المؤسسة؟",
               "example": "Grundschule am Mühlenberg"},
        "tr": {"question": "Okul, kreş veya kurumun adı nedir?",
               "example": "Grundschule am Mühlenberg"},
        "de": {"question": "Wie lautet der Name der Schule / Kita / Einrichtung?",
               "example": "Grundschule am Mühlenberg"},
        "es": {"question": "¿Cuál es el nombre de la escuela, guardería o institución?",
               "example": "Grundschule am Mühlenberg"},
        "sq": {"question": "Cili është emri i shkollës, kopshtit ose institucjonit?",
               "example": "Grundschule am Mühlenberg"},
        "ru": {"question": "Как называется школа, детский сад или учреждение?",
               "example": "Grundschule am Mühlenberg"},
        "uk": {"question": "Як називається школа, дитячий садок або установа?",
               "example": "Grundschule am Mühlenberg"},
    },

    # ── Transport ─────────────────────────────────────────────────────────────

    "transport.start_location": {
        "en": {"question": "Where does the journey start?",
               "help": "Write the city, address, or name of the place where the trip begins.",
               "example": "Rostock, Hauptbahnhof"},
        "fr": {"question": "D'où part le trajet ?",
               "help": "Écrivez la ville ou l'adresse de départ.",
               "example": "Rostock, Hauptbahnhof"},
        "ar": {"question": "من أين تبدأ الرحلة؟",
               "help": "اكتب المدينة أو عنوان نقطة البداية.",
               "example": "روستوك"},
        "tr": {"question": "Yolculuk nereden başlıyor?",
               "help": "Başlangıç noktasının adını veya adresini yazın.",
               "example": "Rostock, Hauptbahnhof"},
        "de": {"question": "Wo beginnt die Fahrt?",
               "help": "Ort oder Adresse des Abfahrtspunkts eintragen.",
               "example": "Rostock, Hauptbahnhof"},
        "es": {"question": "¿Dónde comienza el viaje?",
               "example": "Rostock, Hauptbahnhof"},
        "sq": {"question": "Ku fillon udhëtimi?",
               "example": "Rostock, Hauptbahnhof"},
        "ru": {"question": "Откуда начинается поездка?",
               "example": "Росток, Hauptbahnhof"},
        "uk": {"question": "Звідки починається поїздка?",
               "example": "Росток, Hauptbahnhof"},
    },

    "transport.destination": {
        "en": {"question": "Where does the journey end?",
               "help": "Write the destination — for example the school, Kita, or training place.",
               "example": "Berufsschule Rostock, Möllner Straße 5"},
        "fr": {"question": "Où se termine le trajet ?",
               "help": "Écrivez la destination — par exemple l'école ou la crèche.",
               "example": "Berufsschule Rostock"},
        "ar": {"question": "أين تنتهي الرحلة؟",
               "help": "اكتب الوجهة، مثلاً المدرسة أو الحضانة.",
               "example": "Berufsschule Rostock"},
        "tr": {"question": "Yolculuk nerede bitiyor?",
               "help": "Varış noktasını yazın — örneğin okul veya kreş.",
               "example": "Berufsschule Rostock"},
        "de": {"question": "Wo endet die Fahrt?",
               "help": "Ziel eintragen — z.B. Schule, Kita oder Ausbildungsort.",
               "example": "Berufsschule Rostock, Möllner Straße 5"},
        "es": {"question": "¿Dónde termina el viaje?",
               "example": "Berufsschule Rostock"},
        "sq": {"question": "Ku përfundon udhëtimi?",
               "example": "Berufsschule Rostock"},
        "ru": {"question": "Где заканчивается поездка?",
               "example": "Berufsschule Rostock"},
        "uk": {"question": "Де закінчується поїздка?",
               "example": "Berufsschule Rostock"},
    },

    "transport.distance_km": {
        "en": {"question": "How many kilometres is the one-way journey from home to school?",
               "help": "Write only the one-way distance, not the round trip.",
               "format": "Number only, e.g. 5", "example": "5"},
        "fr": {"question": "Combien de kilomètres y a-t-il entre le domicile et l'école (aller simple) ?",
               "format": "Un nombre, p.ex. 5", "example": "5"},
        "ar": {"question": "كم كيلومتراً المسافة ذهاباً فقط من المنزل إلى المدرسة؟",
               "format": "رقم فقط، مثلاً 5", "example": "5"},
        "tr": {"question": "Evden okula kaç kilometre (tek yön)?",
               "format": "Sadece rakam, örn. 5", "example": "5"},
        "de": {"question": "Wie viele Kilometer beträgt die einfache Strecke zur Schule?",
               "format": "Nur Zahl, z.B. 5", "example": "5"},
        "es": {"question": "¿Cuántos kilómetros hay entre el domicilio y la escuela (solo ida)?",
               "format": "Solo número, ej. 5", "example": "5"},
        "sq": {"question": "Sa kilometra është rruga vetëm njëdrejt nga shtëpia në shkollë?",
               "format": "Vetëm numër, p.sh. 5", "example": "5"},
        "ru": {"question": "Сколько километров составляет путь от дома до школы в одну сторону?",
               "format": "Только число, например 5", "example": "5"},
        "uk": {"question": "Скільки кілометрів від будинку до школи в один бік?",
               "format": "Тільки число, наприклад 5", "example": "5"},
    },

    "transport.cost_eur": {
        "en": {"question": "How much does the transport cost (in Euros)?",
               "format": "Number with cents, e.g. 29.50", "example": "29.50"},
        "fr": {"question": "Combien coûte le transport (en euros) ?",
               "format": "Nombre avec centimes, p.ex. 29,50", "example": "29,50"},
        "ar": {"question": "كم تكلفة المواصلات (باليورو)؟",
               "format": "رقم مع سنتات، مثلاً 29.50", "example": "29.50"},
        "tr": {"question": "Ulaşım ne kadar tutuyor (Euro)?",
               "format": "Kuruşlu sayı, örn. 29,50", "example": "29,50"},
        "de": {"question": "Wie hoch sind die Beförderungskosten (in Euro)?",
               "format": "Betrag in Euro, z.B. 29,50", "example": "29,50"},
        "es": {"question": "¿Cuánto cuesta el transporte (en euros)?",
               "format": "Número con céntimos, ej. 29,50", "example": "29,50"},
        "sq": {"question": "Sa kushton transporti (në Euro)?",
               "format": "Numër me centë, p.sh. 29,50", "example": "29,50"},
        "ru": {"question": "Сколько стоит транспортировка (в евро)?",
               "format": "Число с центами, напр. 29,50", "example": "29,50"},
        "uk": {"question": "Скільки коштує перевезення (в євро)?",
               "format": "Число з центами, напр. 29,50", "example": "29,50"},
    },

    "transport.traveler_count": {
        "en": {"question": "How many people will travel?",
               "help": "Count every person who will use this transport.",
               "format": "Write only a number.", "example": "2"},
        "fr": {"question": "Combien de personnes vont voyager ?",
               "help": "Comptez chaque personne qui utilisera ce transport.",
               "format": "Écrivez uniquement un nombre.", "example": "2"},
        "ar": {"question": "كم عدد الأشخاص الذين سيسافرون؟",
               "format": "اكتب رقماً فقط.", "example": "2"},
        "tr": {"question": "Kaç kişi yolculuk yapacak?",
               "format": "Sadece sayı yazın.", "example": "2"},
        "de": {"question": "Wie viele Personen reisen?",
               "format": "Nur Zahl eintragen.", "example": "2"},
        "es": {"question": "¿Cuántas personas viajarán?",
               "format": "Escribe solo un número.", "example": "2"},
        "sq": {"question": "Sa persona do të udhëtojnë?",
               "format": "Shkruani vetëm një numër.", "example": "2"},
        "ru": {"question": "Сколько человек будет ехать?",
               "format": "Напишите только число.", "example": "2"},
        "uk": {"question": "Скільки людей будуть їхати?",
               "format": "Напишіть тільки число.", "example": "2"},
    },

    # ── Amount ────────────────────────────────────────────────────────────────

    "amount.eur": {
        "en": {"question": "What is the amount in Euros?",
               "format": "Write a number with cents, e.g. 25.50", "example": "25.50"},
        "fr": {"question": "Quel est le montant en euros ?",
               "format": "Écrivez un nombre avec centimes, p.ex. 25,50", "example": "25,50"},
        "ar": {"question": "ما هو المبلغ باليورو؟",
               "format": "رقم مع سنتات، مثلاً 25.50", "example": "25.50"},
        "tr": {"question": "Euro cinsinden miktar nedir?",
               "format": "Kuruşlu sayı, örn. 25,50", "example": "25,50"},
        "de": {"question": "Wie hoch ist der Betrag in Euro?",
               "format": "Betrag in Euro, z.B. 25,50", "example": "25,50"},
        "es": {"question": "¿Cuál es el importe en euros?",
               "format": "Número con céntimos, ej. 25,50", "example": "25,50"},
        "sq": {"question": "Sa është shuma në Euro?",
               "format": "Numër me centë, p.sh. 25,50", "example": "25,50"},
        "ru": {"question": "Какова сумма в евро?",
               "format": "Число с центами, напр. 25,50", "example": "25,50"},
        "uk": {"question": "Яка сума в євро?",
               "format": "Число з центами, напр. 25,50", "example": "25,50"},
    },

    "amount.count": {
        "en": {"question": "How many? (write only a number)",
               "format": "Write only a number, e.g. 3", "example": "3"},
        "fr": {"question": "Combien ? (écrivez seulement un nombre)",
               "format": "Écrivez uniquement un nombre, p.ex. 3", "example": "3"},
        "ar": {"question": "كم عدداً؟ (اكتب رقماً فقط)",
               "format": "اكتب رقماً فقط، مثلاً 3", "example": "3"},
        "tr": {"question": "Kaç tane? (sadece sayı yazın)",
               "format": "Sadece sayı yazın, örn. 3", "example": "3"},
        "de": {"question": "Wie viele? (nur Zahl eintragen)",
               "format": "Nur Zahl eintragen, z.B. 3", "example": "3"},
        "es": {"question": "¿Cuántos? (escribe solo un número)",
               "format": "Escribe solo un número, ej. 3", "example": "3"},
        "sq": {"question": "Sa? (shkruani vetëm një numër)",
               "format": "Shkruani vetëm një numër, p.sh. 3", "example": "3"},
        "ru": {"question": "Сколько? (напишите только число)",
               "format": "Напишите только число, напр. 3", "example": "3"},
        "uk": {"question": "Скільки? (напишіть тільки число)",
               "format": "Напишіть тільки число, напр. 3", "example": "3"},
    },

    # ── Date components ───────────────────────────────────────────────────────

    "date.day": {
        "en": {"question": "What day of the month are you filling out this form?",
               "help": "Write only the day number — not the full date.",
               "format": "Number from 1 to 31",
               "example": "If today is 6 May 2026, write: 6"},
        "fr": {"question": "Quel jour du mois remplissez-vous ce formulaire ?",
               "help": "Écrivez uniquement le numéro du jour.",
               "format": "Nombre de 1 à 31",
               "example": "Si aujourd'hui c'est le 6 mai 2026, écrivez : 6"},
        "ar": {"question": "ما هو يوم الشهر الذي تملأ فيه هذا النموذج؟",
               "format": "رقم من 1 إلى 31",
               "example": "إذا كان اليوم 6 مايو 2026، اكتب: 6"},
        "tr": {"question": "Bu formu doldurduğunuz ayın kaçıdır?",
               "format": "1 ile 31 arasında bir sayı",
               "example": "Bugün 6 Mayıs 2026 ise yazın: 6"},
        "de": {"question": "An welchem Tag des Monats füllen Sie dieses Formular aus?",
               "format": "Zahl von 1 bis 31",
               "example": "Heute ist der 6. Mai 2026 → eintragen: 6"},
        "es": {"question": "¿Qué día del mes estás rellenando este formulario?",
               "format": "Número del 1 al 31",
               "example": "Si hoy es 6 de mayo de 2026, escribe: 6"},
        "sq": {"question": "Cilin ditë të muajit po plotësoni këtë formular?",
               "format": "Numër nga 1 deri 31",
               "example": "Nëse sot është 6 maj 2026, shkruani: 6"},
        "ru": {"question": "Какое число месяца вы заполняете эту форму?",
               "format": "Число от 1 до 31",
               "example": "Если сегодня 6 мая 2026, напишите: 6"},
        "uk": {"question": "Яке число місяця ви заповнюєте цю форму?",
               "format": "Число від 1 до 31",
               "example": "Якщо сьогодні 6 травня 2026, напишіть: 6"},
    },

    "date.month": {
        "en": {"question": "What month are you filling out this form?",
               "help": "Write the month number (1–12) or the month name.",
               "example": "If today is 6 May 2026, write: 5 or May"},
        "fr": {"question": "Quel mois remplissez-vous ce formulaire ?",
               "help": "Écrivez le numéro du mois (1 à 12) ou le nom du mois.",
               "example": "Si aujourd'hui c'est le 6 mai 2026, écrivez : 5 ou mai"},
        "ar": {"question": "ما هو الشهر الذي تملأ فيه هذا النموذج؟",
               "example": "إذا كان اليوم 6 مايو 2026، اكتب: 5 أو مايو"},
        "tr": {"question": "Bu formu doldurduğunuz ay kaçıdır?",
               "example": "Bugün 6 Mayıs 2026 ise yazın: 5 veya Mayıs"},
        "de": {"question": "In welchem Monat füllen Sie dieses Formular aus?",
               "example": "Heute ist Mai 2026 → eintragen: 5 oder Mai"},
        "es": {"question": "¿En qué mes estás rellenando este formulario?",
               "example": "Si hoy es 6 de mayo de 2026, escribe: 5 o mayo"},
        "sq": {"question": "Cilin muaj po plotësoni këtë formular?",
               "example": "Nëse sot është 6 maj 2026, shkruani: 5 ose maj"},
        "ru": {"question": "В каком месяце вы заполняете эту форму?",
               "example": "Если сегодня 6 мая 2026, напишите: 5 или май"},
        "uk": {"question": "В якому місяці ви заповнюєте цю форму?",
               "example": "Якщо сьогодні 6 травня 2026, напишіть: 5 або травень"},
    },

    "date.year": {
        "en": {"question": "What year are you filling out this form?",
               "help": "Write the full 4-digit year.",
               "format": "4-digit year", "example": "2026"},
        "fr": {"question": "En quelle année remplissez-vous ce formulaire ?",
               "format": "Année complète (4 chiffres)", "example": "2026"},
        "ar": {"question": "ما هو العام الذي تملأ فيه هذا النموذج؟",
               "format": "4 أرقام", "example": "2026"},
        "tr": {"question": "Bu formu doldurduğunuz yıl nedir?",
               "format": "4 haneli yıl", "example": "2026"},
        "de": {"question": "In welchem Jahr füllen Sie dieses Formular aus?",
               "format": "4-stellige Jahreszahl", "example": "2026"},
        "es": {"question": "¿En qué año estás rellenando este formulario?",
               "format": "Año de 4 dígitos", "example": "2026"},
        "sq": {"question": "Cilin vit po plotësoni këtë formular?",
               "format": "Vit me 4 shifra", "example": "2026"},
        "ru": {"question": "В каком году вы заполняете эту форму?",
               "format": "4-значный год", "example": "2026"},
        "uk": {"question": "В якому році ви заповнюєте цю форму?",
               "format": "4-значний рік", "example": "2026"},
    },

    # ── Bank ──────────────────────────────────────────────────────────────────

    "bank.iban": {
        "en": {"question": "What is your IBAN (bank account number)?",
               "help": "The IBAN is on your bank statement or online banking.",
               "format": "Starts with 2 letters then numbers, e.g. DE89...",
               "example": "DE89 3704 0044 0532 0130 00"},
        "fr": {"question": "Quel est votre IBAN (numéro de compte bancaire) ?",
               "example": "DE89 3704 0044 0532 0130 00"},
        "ar": {"question": "ما هو رقم حسابك المصرفي الدولي (IBAN)؟",
               "example": "DE89 3704 0044 0532 0130 00"},
        "tr": {"question": "IBAN numaranız nedir?",
               "example": "DE89 3704 0044 0532 0130 00"},
        "de": {"question": "Wie lautet Ihre IBAN?",
               "example": "DE89 3704 0044 0532 0130 00"},
        "es": {"question": "¿Cuál es tu IBAN (número de cuenta bancaria)?",
               "example": "DE89 3704 0044 0532 0130 00"},
        "sq": {"question": "Cili është IBAN-i juaj (numri i llogarisë bankare)?",
               "example": "DE89 3704 0044 0532 0130 00"},
        "ru": {"question": "Каков ваш IBAN (международный номер банковского счёта)?",
               "example": "DE89 3704 0044 0532 0130 00"},
        "uk": {"question": "Який ваш IBAN (міжнародний номер банківського рахунку)?",
               "example": "DE89 3704 0044 0532 0130 00"},
    },

    "bank.bic": {
        "en": {"question": "What is the BIC/SWIFT code of your bank?",
               "help": "The BIC is on your bank statement or the bank's website.",
               "example": "COBADEFFXXX"},
        "fr": {"question": "Quel est le code BIC/SWIFT de votre banque ?",
               "example": "COBADEFFXXX"},
        "ar": {"question": "ما هو رمز BIC/SWIFT لبنكك؟",
               "example": "COBADEFFXXX"},
        "tr": {"question": "Bankanızın BIC/SWIFT kodu nedir?",
               "example": "COBADEFFXXX"},
        "de": {"question": "Wie lautet die BIC/SWIFT-Kennung Ihrer Bank?",
               "example": "COBADEFFXXX"},
        "es": {"question": "¿Cuál es el código BIC/SWIFT de tu banco?",
               "example": "COBADEFFXXX"},
        "sq": {"question": "Cili është kodi BIC/SWIFT i bankës tuaj?",
               "example": "COBADEFFXXX"},
        "ru": {"question": "Каков BIC/SWIFT-код вашего банка?",
               "example": "COBADEFFXXX"},
        "uk": {"question": "Який BIC/SWIFT-код вашого банку?",
               "example": "COBADEFFXXX"},
    },

    # ── Submission ────────────────────────────────────────────────────────────

    "submission.date": {
        "en": {"question": "What is today's date?",
               "help": "Write the date you are filling out this form.",
               "format": "DD.MM.YYYY", "example": "06.05.2026"},
        "fr": {"question": "Quelle est la date d'aujourd'hui ?",
               "format": "JJ.MM.AAAA", "example": "06.05.2026"},
        "ar": {"question": "ما هو تاريخ اليوم؟",
               "format": "يوم.شهر.سنة", "example": "06.05.2026"},
        "tr": {"question": "Bugünün tarihi nedir?",
               "format": "GG.AA.YYYY", "example": "06.05.2026"},
        "de": {"question": "Was ist das heutige Datum?",
               "format": "TT.MM.JJJJ", "example": "06.05.2026"},
        "es": {"question": "¿Cuál es la fecha de hoy?",
               "format": "DD.MM.AAAA", "example": "06.05.2026"},
        "sq": {"question": "Cila është data e sotme?",
               "format": "DD.MM.VVVV", "example": "06.05.2026"},
        "ru": {"question": "Какова сегодняшняя дата?",
               "format": "ДД.ММ.ГГГГ", "example": "06.05.2026"},
        "uk": {"question": "Яка сьогоднішня дата?",
               "format": "ДД.ММ.РРРР", "example": "06.05.2026"},
    },

    "submission.place_date": {
        "en": {"question": "What city and date should appear next to your signature?",
               "help": "Write the city where you are submitting the form, followed by today's date.",
               "example": "Rostock, 06.05.2026"},
        "fr": {"question": "Quelle ville et quelle date doivent figurer à côté de votre signature ?",
               "example": "Rostock, 06.05.2026"},
        "ar": {"question": "ما هي المدينة والتاريخ بجوار توقيعك؟",
               "example": "Rostock, 06.05.2026"},
        "tr": {"question": "İmzanızın yanında hangi şehir ve tarih görünmeli?",
               "example": "Rostock, 06.05.2026"},
        "de": {"question": "Welcher Ort und welches Datum stehen neben Ihrer Unterschrift?",
               "example": "Rostock, 06.05.2026"},
        "es": {"question": "¿Qué ciudad y fecha deben aparecer junto a tu firma?",
               "example": "Rostock, 06.05.2026"},
        "sq": {"question": "Cili qytet dhe data duhet të shfaqen pranë nënshkrimit tuaj?",
               "example": "Rostock, 06.05.2026"},
        "ru": {"question": "Какой город и дата должны стоять рядом с вашей подписью?",
               "example": "Росток, 06.05.2026"},
        "uk": {"question": "Яке місто і дата повинні стояти поруч з вашим підписом?",
               "example": "Росток, 06.05.2026"},
    },

    "submission.signature": {
        "en": {"question": "Please sign here after printing.",
               "help": "You must sign this by hand after you download and print the form."},
        "fr": {"question": "Veuillez signer ici après impression.",
               "help": "Vous devez signer à la main après avoir téléchargé et imprimé le formulaire."},
        "ar": {"question": "يرجى التوقيع هنا بعد الطباعة.",
               "help": "يجب أن توقع بخط يدك بعد تنزيل النموذج وطباعته."},
        "tr": {"question": "Lütfen yazdırdıktan sonra burayı imzalayın.",
               "help": "Formu indirip yazdırdıktan sonra elle imzalamanız gerekir."},
        "de": {"question": "Bitte nach dem Drucken hier unterschreiben.",
               "help": "Die Unterschrift muss handschriftlich nach dem Ausdrucken geleistet werden."},
        "es": {"question": "Por favor firme aquí después de imprimir.",
               "help": "Debe firmar a mano después de descargar e imprimir el formulario."},
        "sq": {"question": "Ju lutemi nënshkruani këtu pasi të keni printuar.",
               "help": "Duhet të nënshkruani me dorë pasi të keni shkarkuar dhe printuar formularin."},
        "ru": {"question": "Пожалуйста, подпишите здесь после распечатки.",
               "help": "Вы должны подписать от руки после скачивания и распечатки формы."},
        "uk": {"question": "Будь ласка, підпишіть тут після друку.",
               "help": "Ви повинні підписати від руки після завантаження та друку форми."},
    },

    # ── Jobcenter ─────────────────────────────────────────────────────────────

    "jobcenter.bg_number": {
        "en": {"question": "What is your Jobcenter case number (BG-Nummer)?",
               "help": "This number is on letters from the Jobcenter. Usually at the top right.",
               "example": "12345BG0001234"},
        "fr": {"question": "Quel est votre numéro de dossier Jobcenter (BG-Nummer) ?",
               "help": "Ce numéro figure sur les courriers du Jobcenter.",
               "example": "12345BG0001234"},
        "ar": {"question": "ما هو رقم ملفك في مركز العمل (BG-Nummer)؟",
               "example": "12345BG0001234"},
        "tr": {"question": "Jobcenter dosya numaranız (BG-Nummer) nedir?",
               "example": "12345BG0001234"},
        "de": {"question": "Wie lautet Ihre BG-Nummer?",
               "help": "Auf Schreiben des Jobcenters, meist oben rechts.",
               "example": "12345BG0001234"},
        "es": {"question": "¿Cuál es tu número de expediente del Jobcenter (BG-Nummer)?",
               "example": "12345BG0001234"},
        "sq": {"question": "Cili është numri juaj i dosjes në Jobcenter (BG-Nummer)?",
               "example": "12345BG0001234"},
        "ru": {"question": "Каков ваш номер дела в Jobcenter (BG-Nummer)?",
               "example": "12345BG0001234"},
        "uk": {"question": "Який ваш номер справи в Jobcenter (BG-Nummer)?",
               "example": "12345BG0001234"},
    },
}


# ── Label → semantic_key inference ───────────────────────────────────────────
# Keyed by lowercase cleaned German label. Applied after extraction as annotation.

LABEL_TO_SEMANTIC: dict[str, str] = {
    # Person
    "name":                     "person.full_name",
    "vorname":                  "person.first_name",
    "nachname":                 "person.last_name",
    "familienname":             "person.last_name",
    "geburtsdatum":             "person.birth_date",
    "geburtsort":               "person.birth_place",
    "geburtsname":              "person.birth_name",
    "staatsangehörigkeit":      "person.nationality",
    "staatsangehorigkeit":      "person.nationality",
    "nationalität":             "person.nationality",
    "nationalitat":             "person.nationality",
    "familienstand":            "person.marital_status",
    "geschlecht":               "person.gender",
    # Address
    "straße":                   "address.street",
    "strasse":                  "address.street",
    "hausnummer":               "address.house_number",
    "postleitzahl":             "address.postal_code",
    "plz":                      "address.postal_code",
    "ort":                      "address.city",
    "wohnort":                  "address.city",
    "stadt":                    "address.city",
    "land":                     "address.country",
    # Contact
    "telefon":                  "contact.phone",
    "telefonnummer":            "contact.phone",
    "mobilnummer":              "contact.phone",
    "e-mail":                   "contact.email",
    "email":                    "contact.email",
    # Child
    "klasse":                   "child.class_grade",
    "schuljahr":                "child.school_year",
    # Transport
    "startort":                 "transport.start_location",
    "zielort":                  "transport.destination",
    "einfache strecke in km":   "transport.distance_km",
    "strecke":                  "transport.distance_km",
    "anzahl reisende":          "transport.traveler_count",
    "anzahl der reisenden":     "transport.traveler_count",
    # Amount
    "betrag":                   "amount.eur",
    "anzahl":                   "amount.count",
    # Date components
    "tag":                      "date.day",
    "monat":                    "date.month",
    "jahr":                     "date.year",
    "uhrzeit":                  "date.time",
    # Bank
    "iban":                     "bank.iban",
    "bic":                      "bank.bic",
    # Submission
    "datum":                    "submission.date",
    "ort datum":                "submission.place_date",
    "ort, datum":               "submission.place_date",
    "unterschrift":             "submission.signature",
}


def infer_semantic_key(original_label: str) -> Optional[str]:
    """Return a semantic_key for a common German label, or None."""
    import re
    # Normalize: lowercase, strip trailing numbers, collapse spaces
    lo = re.sub(r'\s+\d+$', '', original_label.strip()).strip().lower()
    return LABEL_TO_SEMANTIC.get(lo)


def lookup_semantic(semantic_key: str, locale: str) -> Optional[dict[str, str]]:
    """Return {question, help, example, format} for a semantic key + locale, or None."""
    entry = SEMANTIC_QUESTIONS.get(semantic_key)
    if not entry:
        return None
    return entry.get(locale) or entry.get("en")
